version = 0.1
[default]
[default.pipeline_bootstrap]
[default.pipeline_bootstrap.parameters]
pipeline_user = "arn:aws:iam::780401591112:user/aws-sam-cli-managed-dev-pipeline-reso-PipelineUser-PQTG4CND0MPJ"

[dev]
[dev.pipeline_bootstrap]
[dev.pipeline_bootstrap.parameters]
pipeline_execution_role = "arn:aws:iam::780401591112:role/aws-sam-cli-managed-dev-pipe-PipelineExecutionRole-1XAFRXB6BG7KK"
cloudformation_execution_role = "arn:aws:iam::780401591112:role/aws-sam-cli-managed-dev-p-CloudFormationExecutionR-MZVH5W6GR64V"
artifacts_bucket = "aws-sam-cli-managed-dev-pipeline-artifactsbucket-1a7ac8xiti4g9"
image_repository = ""
region = "us-west-2"

[prod]
[prod.pipeline_bootstrap]
[prod.pipeline_bootstrap.parameters]
pipeline_execution_role = "arn:aws:iam::780401591112:role/aws-sam-cli-managed-prod-pip-PipelineExecutionRole-1SUMADI1XT76P"
cloudformation_execution_role = "arn:aws:iam::780401591112:role/aws-sam-cli-managed-prod-CloudFormationExecutionR-OY344GDLB2NL"
artifacts_bucket = "aws-sam-cli-managed-prod-pipeline-artifactsbucket-1mgd2f7jh27oy"
image_repository = ""
region = "us-west-2"
